---
title: "Géomatique avec R - raster"
subtitle: "Le package `terra` pour manipuler les données géographiques RASTER"
author: 
- Hugues pecout
- Timothée Giraud
date: last-modified
ordre: 02
code-fold: true
code-tools: true
---

## Introduction

Cette leçon vise à initier à la gestion, l'analyse et la représentation de données géographiques matricielles (raster) avec le package `terra`. Les différentes manipulations de données matricielles abordées sont :

-   Import et export de raster
-   Affichage graphique de raster
-   Modification d'un raster (reprojection, découpage, aggrégation, fusion...)
-   Algèbre spatial (locale, focale, zonales et globale)
-   Transformation et conversion de raster

## <i class="bi bi-book"></i> Manuel {.title}

<iframe class="slide" src="https://rcarto.github.io/geomatique_avec_r/les-donn%C3%A9es-raster-le-package-terra.html">

</iframe>

\

::: callout-note
Ce support de ce cours est un manuel initialement conçu pour accompagner le cours *'Cartographie avec R'* du Master 2 Géomatique, géodécisionnel, géomarketing et multimédia (G2M) de l'Université Paris 8 Vincennes - Saint-Denis (France). Vous pouvez envoyer vos remarques et suggestions aux auteurs en [postant une issue](https://github.com/rCarto/geomatique_avec_r/issues) sur le [dépôt GitHub](https://github.com/rCarto/geomatique_avec_r) de ce document.
:::

\


## <i class="bi bi-person-workspace"></i> Exercice {.title .exo-title}

::: {#exo}
:::

\
