project:
  type: website
lang: fr
website:
  title: "<b>TIG'R</b>"
  favicon: img/tigr2.png
  twitter-card: true
  site-url: https://tigr.netlify.app/
  description: "Modules de formation pour le traitement de l'information géographique avec R"
  page-navigation: true
  search:
    location: sidebar

  sidebar:
    style: "docked"
    contents:
    
      - text: "**Introduction**"
        href: presentation.qmd
        
      - text: "---"
      
      - text:  "**Données utilisées**"
        href: data.qmd

          # - href: packages.qmd
          #   text: Packages utilisés

      - text: "---"

      - section: "**Import de données**"
        contents:
          - href: modules/import.qmd
            text: Introduction
          - href: modules/import/import.qmd
            text: Import & export
          - href: modules/import/api.qmd
            text: Package & API
          - href: modules/import/osm.qmd
            text: OpenStreetMap
          - href: modules/import/scraping.qmd 
            text: Web scraping
            
      - section: "**Manipulation**"
        contents:
          - href: modules/manipulation.qmd
            text: Introduction
          - href: modules/manipulation/manipulation.qmd
            text: R-base
          - href: modules/manipulation/datatable.qmd
            text: data.table
          - href: modules/manipulation/tidyverse.qmd 
            text: tidyverse
            
      - section: "**Graphique**"
        contents:
          - href: modules/graphique.qmd
            text: Introduction
          - href: modules/graphique/Rbase_graph.qmd
            text: Graphique R-base
          - href: modules/graphique/ggplot2.qmd
            text: Graphique avec ggplot2
          - href: modules/graphique/package_graph.qmd 
            text: Divers
            
      - section: "**Statistique**"
        contents:
          - href: modules/statistique.qmd
            text: Introduction
          - href: modules/statistique/statistique_uni.qmd
            text: Univariée
          - href: modules/statistique/statistique_bi.qmd
            text: Bivariée
          - href: modules/statistique/statistique_multi.qmd
            text: Multivariée
          
      - section: "**Géomatique**"
        contents:
          - href: modules/geomatique.qmd
            text: Introduction
          - href: modules/geomatique/geomatic_vector.qmd
            text: Données vectorielles
          - href: modules/geomatique/geomatic_raster.qmd
            text: Données Raster
            
      - section: "**Cartographie**"
        contents:
          - href: modules/cartographie.qmd
            text: Introduction
          - href: modules/cartographie/map_sf.qmd
            text: Cartographie statique
          - href: modules/cartographie/map_2.qmd
            text: Cartographie dynamique              
            
      - section: "**Notebook**"
        contents:
          - href: modules/notebook.qmd
            text: Introduction
          - href: modules/notebook/programmation_lettree.qmd
            text: La programmation lettrée
          - href: modules/notebook/notebook.qmd
            text: Les notebooks  
          - href: modules/notebook/quarto.qmd
            text: Exemple Quarto    
            
      - text: "---"
      
      - text: "**Ressources annexes**"
        href: ressources.qmd
            
  navbar:
    background: "#2a8cbe"
    left: 
      - text: Introduction 
        href: presentation.qmd
      - text: Données 
        href: data.qmd
      # - text: Packages
      #   href: packages.qmd
      - text: Modules
        href: modules.qmd       
      - text: Ressources externes
        href: ressources.qmd

        
    right:    
      - href: about.qmd
        text: Crédits
        
    tools:
      - icon: github
        aria-label: GitHub
        text: GitHub
        href: https://github.com/HuguesPecout/Modules_R
        

  page-footer:  Ecole d'été CIST·2023 - [![licensebuttons by-sa](https://licensebuttons.net/l/by-sa/4.0/80x15.png)](https://creativecommons.org/licenses/by-sa/4.0) - UMR8504 Géographie-Cités 
  # margin-header: |
  #   ![](img/logo.png){width="90%"}
  
format:
  html:
    theme: 
      light: Cosmo
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full

editor: visual
  
  

