project:
  type: website
lang: fr
website:
  title: "<b>T·I·G·R</b>"
  favicon: img/cist.png
  twitter-card: true
  site-url: https://ee-cist.github.io/modules_R/
  description: "Modules de formation pour le traitement de l'information géographique avec R"
  page-navigation: true
  search:
    location: sidebar
    
  sidebar:
    style: "docked"
    contents:
      - section: "**Données**"
        contents:
          - href: data.qmd
            text: A
          - href: data1.qmd
            text: B
          - href: data2.qmd
            text: C
            
      - section: "**Import**"
        contents:
          - href: import.qmd
            text: Import & export
          - href: api.qmd
            text: Packages API
          - href: scraping.qmd 
            text: Web scraping
            
      - section: "**Manipulation**"
        contents:
          - href: manipulation.qmd
            text: R-base
          - href: datatable.qmd
            text: data.table
          - href: tidyverse.qmd 
            text: tidyverse
            
      - section: "**Statistique**"
        contents:
          - href: statistique.qmd
            text: Univariée
          - href: statistique2.qmd
            text: Bivariée
          - href: statistique3.qmd
            text: Multivariée
            
      - section: "**Cartographie**"
        contents:
          - href: map.qmd
            text: Cartographie statique
          - href: map2.qmd
            text: Cartographie dynamique   
            
      - section: "**Géomatique**"
        contents:
          - href: geomatic.qmd
            text: Données vectorielles
          - href: geomatic2.qmd
            text: Données Raster
          
      - section: "**Notebook**"
        contents:
          - href: programmation_lettree.qmd
            text: La programmation lettrée
          - href: notebook.qmd
            text: Les notebooks  
          - href: quarto.qmd
            text: Présentation de Quarto        
  navbar:
    background: "#1a8cab"
    left: 
      - text: Données
        menu:
          - href: data.qmd
            text: A
          - href: data1.qmd
            text: B
          - href: data2.qmd
            text: C
            
      - text: Import
        menu:
          - href: import.qmd
            text: Import & export
          - href: api.qmd
            text: Packages API
          - href: scraping.qmd 
            text: Web scraping
            
      - text: Manipulation
        menu:
          - href: manipulation.qmd
            text: R-base
          - href: datatable.qmd
            text: data.table
          - href: tidyverse.qmd 
            text: tidyverse
            
      - text: Statistique
        menu:
          - href: statistique.qmd
            text: Univariée
          - href: statistique2.qmd
            text: Bivariée
          - href: statistique3.qmd
            text: Multivariée
            
      - text : Cartographie
        menu:
          - href: map.qmd
            text: Cartographie statique
          - href: map2.qmd
            text: Cartographie dynamique   
            
      - text : Géomatique
        menu:
          - href: geomatic.qmd
            text: Données vectorielles
          - href: geomatic2.qmd
            text: Données Raster
          
      - text : Notebook
        menu:
          - href: programmation_lettree.qmd
            text: La programmation lettrée
          - href: notebook.qmd
            text: Les notebooks  
          - href: quarto.qmd
            text: Présentation de Quarto 
 
        
    right:
      - href: ressources.qmd
        text: Ressources
      - href: about.qmd
        text: Á propos
        
    tools:
      - icon: github
        aria-label: GitHub
        text: GitHub
        href: https://github.com/EE-CIST/modules_R
        

            

  page-footer:  Ecole d'été CIST·2023 - UMR8504 Géographie-Cités - [![licensebuttons by-sa](https://licensebuttons.net/l/by-sa/4.0/80x15.png)](https://creativecommons.org/licenses/by-sa/4.0)
  margin-header: |
    ![](img/cist.png){width="65%"}
format:
  html:
    theme: 
      light: Cosmo
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full

editor: visual
  
  

